# Generated by Django 5.0 on 2024-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/default_profile.png', upload_to='images/profiles', verbose_name='پروفایل'),
        ),
    ]
